Add tfscan for security scanning

diff --git a/.github/workflows/tf-validate-lint.yaml b/.github/workflows/tf-validate-lint.yaml
--- a/.github/workflows/tf-validate-lint.yaml
+++ b/.github/workflows/tf-validate-lint.yaml
@@ -38,6 +38,12 @@ jobs:
         with:
           terraform_version: 1.11.2
 
+      - name: Run tfsec scanner
+        uses: aquasecurity/tfsec-action@v1.0.0
+        with:
+          soft_fail: true # action don't break the build
+          github_token: ${{ github.token }}
+
       - name: Setup TFLint
         uses: terraform-linters/setup-tflint@v4
         with:
@@ -69,8 +75,8 @@ jobs:
       - name: Verify dev.auto.tfvars content
         run: |
           echo "Checking dev/dev.auto.tfvars for specific required values..."
-          grep -F 'project             = "piksel"' dev/dev.auto.tfvars || (echo "Error: 'project = \"piksel\"' not found or changed in dev/dev.auto.tfvars"; exit 1)
-          grep -F 'environment         = "dev"' dev/dev.auto.tfvars || (echo "Error: 'environment = \"dev\"' not found or changed in dev/dev.auto.tfvars"; exit 1)
+          grep 'project\s*=\s*"piksel"' dev/dev.auto.tfvars || (echo "Error: 'project = \"piksel\"' not found or changed in dev/dev.auto.tfvars"; exit 1)
+          grep 'environment\s*=\s*"dev"' dev/dev.auto.tfvars || (echo "Error: 'environment = \"dev\"' not found or changed in dev/dev.auto.tfvars"; exit 1)
           echo "Required values in dev/dev.auto.tfvars verified."
 
       - name: Verify shared.auto.tfvars content
